### ISSUE TITLE
Deploy with zappa

### ISSUE THREAD

**Issue by ivansabik** [ivansabik/botless#6]
A script `botless init` will ask a couple of questions and generate a `zappa_config.json` based on that. Additionally it could be based on a YAML config something like:

```yaml
bots:
  - name: toggl_less_than_min_hours_to_slack
  - params:
    - min_hours: 37
  - run_date: daily
```
